USE [master]
GO

/****** Object:  Database [Development]    Script Date: 8/27/2019 11:27:47 PM ******/
CREATE DATABASE [Development]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Development', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Development.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Development_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Development_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Development].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Development] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Development] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Development] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Development] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Development] SET ARITHABORT OFF 
GO

ALTER DATABASE [Development] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Development] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Development] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Development] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Development] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Development] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Development] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Development] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Development] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Development] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Development] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Development] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Development] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Development] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Development] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Development] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Development] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Development] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Development] SET  MULTI_USER 
GO

ALTER DATABASE [Development] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Development] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Development] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Development] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Development] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Development] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Development] SET  READ_WRITE 
GO